# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/mateus/Área de Trabalho/PDA_PDI"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/mateus/Área de Trabalho/PDA_PDI"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mateus/Área de Trabalho/PDA_PDI/CMakeFiles" "/home/mateus/Área de Trabalho/PDA_PDI/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/mateus/Área de Trabalho/PDA_PDI/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PDA

# Build rule for target.
PDA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PDA
.PHONY : PDA

# fast build rule for target.
PDA/fast:
	$(MAKE) -f CMakeFiles/PDA.dir/build.make CMakeFiles/PDA.dir/build
.PHONY : PDA/fast

PDA_PDI.o: PDA_PDI.cpp.o
.PHONY : PDA_PDI.o

# target to build an object file
PDA_PDI.cpp.o:
	$(MAKE) -f CMakeFiles/PDA.dir/build.make CMakeFiles/PDA.dir/PDA_PDI.cpp.o
.PHONY : PDA_PDI.cpp.o

PDA_PDI.i: PDA_PDI.cpp.i
.PHONY : PDA_PDI.i

# target to preprocess a source file
PDA_PDI.cpp.i:
	$(MAKE) -f CMakeFiles/PDA.dir/build.make CMakeFiles/PDA.dir/PDA_PDI.cpp.i
.PHONY : PDA_PDI.cpp.i

PDA_PDI.s: PDA_PDI.cpp.s
.PHONY : PDA_PDI.s

# target to generate assembly for a file
PDA_PDI.cpp.s:
	$(MAKE) -f CMakeFiles/PDA.dir/build.make CMakeFiles/PDA.dir/PDA_PDI.cpp.s
.PHONY : PDA_PDI.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... PDA"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PDA_PDI.o"
	@echo "... PDA_PDI.i"
	@echo "... PDA_PDI.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

